### ISSUE TITLE
snipped only shows one

### ISSUE THREAD

**Issue by today4king** [aliyun-beta/aliyun-opensearch-python-sdk#1]
this problem was caused by incorrect Summary join in Search.py file line 202
params['index_name'] = ';'.join(self.indexes)
change 2
params['index_name'] = ','.join(self.indexes)

**Comment by kingxsp** [comment]
see [api search doc](https://help.aliyun.com/document_detail/29150.html?spm=5176.doc29140.6.148.UZNZ7X)  "index_name" parameter
